name: monotransapi
services:
  monotransapi:
    public: true
    image: emekaboris/monotransapione:latest
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 2000m
      memory: 5Gi